### ISSUE TITLE
Generate docs in html or at least make the current less ugly

### ISSUE THREAD

**Issue by camilamaia** [camilamaia/scanapi#15]
Current the format is markdown.

**Comment by barbosa** [comment]
Jinja would be a good candidate here. For both Markdown and HTML. 

It also could be an option for the CLI like `--report markdown` or `--report html`.

And in the future, have a even more flexible para like `--template my_beautiful_page.html` where developers can use whatever they want + CSS 💄.

**Comment by barbosa** [comment]
- [ ] Make DocsWriter abstract
- [ ] Create a MarkdownWriter based on the current code
- [ ] Create a ConsoleWriter (for debugging purposes)
- [ ] Create a JSONWriter (that could be used for Markdown and HTML)
- [ ] Create a HTMLWriter: `scanapi -f schema.yml --writer=html --template=bla.html`

**Comment by barbosa** [comment]
@camilamaia I've broken this down to #58, #59, #60 and #61. Do you think we can close this then?

**Comment by camilamaia** [comment]
Sure! I will do that
